server:
  port: 8080

spring:
  application:
    name: book-common
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: 5000

#logging:
#  level:
#    root: info
#    org.mybatis: debug
#    java.sql: debug
#    org.springframework.web: trace